# Generated by Django 3.2.4 on 2021-07-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='by',
            new_name='user',
        ),
    ]
