# Generated by Django 3.2.4 on 2021-06-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_question_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="details",
            field=models.TextField(
                blank=True, help_text="provide any additional details", null=True
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(help_text="Enter your question", max_length=140),
        ),
    ]
