# Generated by Django 3.2.4 on 2021-07-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210619_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(help_text='add your answer to the question'),
        ),
    ]
