# Generated by Django 3.2.4 on 2021-07-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(help_text='add your answer to the question', unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.TextField(blank=True, help_text='provide any additional details', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(help_text='Enter your question', max_length=140, unique=True),
        ),
    ]
