# Generated by Django 3.2.4 on 2021-06-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_profile_middle_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="middle_name",
        ),
    ]
