# Generated by Django 3.2.4 on 2021-06-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20210613_1611"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
